project:
  type: book
  preview:
    port: 4000

book:
  title: "Python Packaging Essentials"
  author: "Joseph Barbier"
  date: today
  downloads: pdf
  repo-url: https://github.com/yellow-sunflower/python-packaging-essentials/
  search: true
  chapters:
    - index.qmd
    - introduction-to-packaging.qmd
    - organize-a-package.qmd
    - handling-dependencies.qmd
    - unit-tests.qmd
    - writing-documentation.qmd
    - errors-and-warnings.qmd
    - github-actions.qmd
    - pre-commit.qmd
    - api-design.qmd
    - publish-to-pypi.qmd

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



