project:
  type: book
  output-dir: docs/
  preview:
    port: 4000

website:
  google-analytics: "G-XXXXXXXX"

book:
  title: "Python Packaging Essentials"
  subtitle: "Practical guide that walks you through creating, organizing, testing, and publishing Python packages."
  downloads: pdf
  license: MIT
  repo-url: https://github.com/y-sunflower/python-packaging-essentials/
  repo-branch: main
  repo-actions: [source, edit, issue]
  search: true
  sidebar:
    tools:
      - icon: github
        href: https://github.com/y-sunflower/python-packagin-essentials
  chapters:
    - index.qmd
    - part: blog/create-a-package/index.qmd
      chapters:
        - blog/create-a-package/introduction-to-packaging.qmd
        - blog/create-a-package/organize-a-package.qmd
        - blog/create-a-package/handling-dependencies.qmd
    - part: blog/code-quality/index.qmd
      chapters:
        - blog/code-quality/unit-tests.qmd
        - blog/code-quality/writing-documentation.qmd
        - blog/code-quality/errors-and-warnings.qmd
        - blog/code-quality/api-design.qmd
    - part: blog/workflow/index.qmd
      chapters:
        - blog/workflow/github-actions.qmd
        - blog/workflow/pre-commit.qmd
        - blog/workflow/publish-to-pypi.qmd
    - contributing.qmd

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
